INSERT INTO INCARCERATION VALUES(1, '7 months', 'United States Penitentiary, Pollock');
INSERT INTO INCARCERATION VALUES(2, 'Life', 'United States Penitentiary, Victorville');
INSERT INTO INCARCERATION VALUES(3, '6 months', 'United States Penitentiary, Big Sandy');
INSERT INTO INCARCERATION VALUES(4, '5 months', 'United States Penitentiary, Canaan');
INSERT INTO INCARCERATION VALUES(5, '2 months', 'United States Penitentiary, Florence ADX');
INSERT INTO INCARCERATION VALUES(6, '39 years', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(7, '34 years', 'United States Penitentiary, Allenwood');
INSERT INTO INCARCERATION VALUES(8, '7 months', 'United States Penitentiary, Pollock');
INSERT INTO INCARCERATION VALUES(9, '12 years', 'United States Penitentiary, Florence High');
INSERT INTO INCARCERATION VALUES(10, '49 years', 'United States Penitentiary, Pollock');
INSERT INTO INCARCERATION VALUES(11, '7 months', 'United States Penitentiary, Beaumont');
INSERT INTO INCARCERATION VALUES(12, '9 months', 'United States Penitentiary, Tucson');
INSERT INTO INCARCERATION VALUES(13, '3 months', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(14, '11 months', 'United States Penitentiary, Atlanta');
INSERT INTO INCARCERATION VALUES(15, '25 years', 'United States Penitentiary, Marion');
INSERT INTO INCARCERATION VALUES(16, '41 years', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(17, '25 years', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(18, '11 months', 'United States Penitentiary, Atwater');
INSERT INTO INCARCERATION VALUES(19, '46 years', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(20, '9 months', 'United States Penitentiary, Canaan');
INSERT INTO INCARCERATION VALUES(21, '9 months', 'United States Penitentiary, McCreary');
INSERT INTO INCARCERATION VALUES(22, '39 years', 'United States Penitentiary, Leavenworth');
INSERT INTO INCARCERATION VALUES(23, '6 months', 'United States Penitentiary, Atlanta');
INSERT INTO INCARCERATION VALUES(24, '20 years', 'United States Penitentiary, Tucson');
INSERT INTO INCARCERATION VALUES(25, '13 years', 'United States Penitentiary, Lompoc');
INSERT INTO INCARCERATION VALUES(26, '10 months', 'Administrative United States Penitentiary, Thomson');
INSERT INTO INCARCERATION VALUES(27, '3 months', 'United States Penitentiary, Canaan');
INSERT INTO INCARCERATION VALUES(28, '3 months', 'United States Penitentiary, Big Sandy');
INSERT INTO INCARCERATION VALUES(29, '35 years', 'United States Penitentiary, Tucson');
INSERT INTO INCARCERATION VALUES(30, '8 months', 'United States Penitentiary, Marion');
INSERT INTO INCARCERATION VALUES(31, '30 years', 'United States Penitentiary, Lewisburg');
INSERT INTO INCARCERATION VALUES(32, '1 months', 'Administrative United States Penitentiary, Thomson');
INSERT INTO INCARCERATION VALUES(33, '5 months', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(34, '11 months', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(35, '42 years', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(36, 'Life', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(37, 'Life', 'United States Penitentiary, Florence ADX');
INSERT INTO INCARCERATION VALUES(38, '4 months', 'United States Penitentiary, Atlanta');
INSERT INTO INCARCERATION VALUES(39, 'Life', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(40, '10 months', 'United States Penitentiary, Tucson');
INSERT INTO INCARCERATION VALUES(41, '6 months', 'United States Penitentiary, Lee');
INSERT INTO INCARCERATION VALUES(42, '38 years', 'United States Penitentiary, Big Sandy');
INSERT INTO INCARCERATION VALUES(43, '6 months', 'United States Penitentiary, Big Sandy');
INSERT INTO INCARCERATION VALUES(44, '2 months', 'United States Penitentiary, Lompoc');
INSERT INTO INCARCERATION VALUES(45, '3 months', 'United States Penitentiary, Tucson');
INSERT INTO INCARCERATION VALUES(46, '41 years', 'United States Penitentiary, Allenwood');
INSERT INTO INCARCERATION VALUES(47, 'Life', 'United States Penitentiary, Allenwood');
INSERT INTO INCARCERATION VALUES(48, '30 years', 'United States Penitentiary, Coleman I & II');
INSERT INTO INCARCERATION VALUES(49, '9 months', 'United States Penitentiary, Beaumont');
INSERT INTO INCARCERATION VALUES(50, '1 months', 'United States Penitentiary, Allenwood');
INSERT INTO INCARCERATION VALUES(51, '7 months', 'United States Penitentiary, Canaan');
INSERT INTO INCARCERATION VALUES(52, 'Life', 'United States Penitentiary, Atlanta');
INSERT INTO INCARCERATION VALUES(53, '7 months', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(54, '5 months', 'Administrative United States Penitentiary, Thomson');
INSERT INTO INCARCERATION VALUES(55, '7 months', 'United States Penitentiary, Victorville');
INSERT INTO INCARCERATION VALUES(56, '6 months', 'United States Penitentiary, Victorville');
INSERT INTO INCARCERATION VALUES(57, '38 years', 'United States Penitentiary, Pollock');
INSERT INTO INCARCERATION VALUES(58, '41 years', 'United States Penitentiary, Big Sandy');
INSERT INTO INCARCERATION VALUES(59, '10 months', 'United States Penitentiary, Victorville');
INSERT INTO INCARCERATION VALUES(60, '45 years', 'United States Penitentiary, Lee');
INSERT INTO INCARCERATION VALUES(61, '3 months', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(62, 'Life', 'United States Penitentiary, Pollock');
INSERT INTO INCARCERATION VALUES(63, '6 months', 'United States Penitentiary, Big Sandy');
INSERT INTO INCARCERATION VALUES(64, '15 years', 'United States Penitentiary, Lee');
INSERT INTO INCARCERATION VALUES(65, '47 years', 'United States Penitentiary, Big Sandy');
INSERT INTO INCARCERATION VALUES(66, '10 months', 'United States Penitentiary, Coleman I & II');
INSERT INTO INCARCERATION VALUES(67, '11 months', 'United States Penitentiary, Coleman I & II');
INSERT INTO INCARCERATION VALUES(68, '4 months', 'United States Penitentiary, Leavenworth');
INSERT INTO INCARCERATION VALUES(69, '3 months', 'United States Penitentiary, Victorville');
INSERT INTO INCARCERATION VALUES(70, '38 years', 'United States Penitentiary, Pollock');
INSERT INTO INCARCERATION VALUES(71, '2 months', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(72, '2 months', 'United States Penitentiary, McCreary');
INSERT INTO INCARCERATION VALUES(73, '11 years', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(74, '20 years', 'United States Penitentiary, McCreary');
INSERT INTO INCARCERATION VALUES(75, '6 months', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(76, '7 months', 'United States Penitentiary, Coleman I & II');
INSERT INTO INCARCERATION VALUES(77, '8 months', 'United States Penitentiary, Florence ADX');
INSERT INTO INCARCERATION VALUES(78, '6 months', 'United States Penitentiary, Pollock');
INSERT INTO INCARCERATION VALUES(79, '38 years', 'United States Penitentiary, Canaan');
INSERT INTO INCARCERATION VALUES(80, '3 months', 'United States Penitentiary, Victorville');
INSERT INTO INCARCERATION VALUES(81, '3 months', 'United States Penitentiary, Allenwood');
INSERT INTO INCARCERATION VALUES(82, '9 months', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(83, '1 months', 'United States Penitentiary, Lee');
INSERT INTO INCARCERATION VALUES(84, '5 months', 'United States Penitentiary, Big Sandy');
INSERT INTO INCARCERATION VALUES(85, '5 months', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(86, '13 years', 'United States Penitentiary, Coleman I & II');
INSERT INTO INCARCERATION VALUES(87, '26 years', 'United States Penitentiary, Coleman I & II');
INSERT INTO INCARCERATION VALUES(88, '10 months', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(89, '17 years', 'United States Penitentiary, Leavenworth');
INSERT INTO INCARCERATION VALUES(90, '26 years', 'United States Penitentiary, McCreary');
INSERT INTO INCARCERATION VALUES(91, '8 months', 'United States Penitentiary, Florence ADX');
INSERT INTO INCARCERATION VALUES(92, '1 months', 'United States Penitentiary, Leavenworth');
INSERT INTO INCARCERATION VALUES(93, '6 months', 'United States Penitentiary, Terre Haute');
INSERT INTO INCARCERATION VALUES(94, '11 years', 'United States Penitentiary, McCreary');
INSERT INTO INCARCERATION VALUES(95, '3 years', 'United States Penitentiary, Beaumont');
INSERT INTO INCARCERATION VALUES(96, '10 months', 'United States Penitentiary, Hazelton†');
INSERT INTO INCARCERATION VALUES(97, '9 months', 'United States Penitentiary, Canaan');
INSERT INTO INCARCERATION VALUES(98, '35 years', 'United States Penitentiary, Coleman I & II');
INSERT INTO INCARCERATION VALUES(99, '3 months', 'United States Penitentiary, Tucson');
INSERT INTO INCARCERATION VALUES(100, '11 months', 'United States Penitentiary, Marion');
